### ISSUE TITLE
DB Schema 구성

### ISSUE THREAD

**Issue by note629** [HaiyoreNyarukoSan/portfolio-for-portfolio#2]
repository -> UserRepository.java, ProjectRepository.java
domain ->  User.java, Project.java

User
------
user_id BIGINT NOT NULL (PK)
user_name VARCHAR() NOT NULL
email VARCHAR() NOT NULL
password VARCHAR() NOT NULL

Project
--------
project_id BIGINT NOT NULL (PK)
title VARCHAR() NOT NULL
content VARCHAR() NOT NULL
create_at DATETIME NOT NULL
update_at DATETIME
presence_of_files BOOLEAN NULL
구성 하겠습니다

**Comment by donggrii** [comment]
- 현재 DB Schema
<img width="677" alt="DB_Schema" src="https://github.com/HaiyoreNyarukoSan/portfolio-for-portfolio/assets/54230911/b6a9f84a-baa4-4cce-a9c9-7e6189899593">
