### ISSUE TITLE
로그인 관리 시스템 작성

### ISSUE THREAD

**Issue by HaiyoreNyarukoSan** [HaiyoreNyarukoSan/portfolio-for-portfolio#20]
"/"나 "/mian"을 호출하면 로그인 상태에 따라 "/projects"나 "/login"을 호출합니다.

**Comment by donggrii** [comment]
- 최종 : "/"로 접근하면 전체 프로젝트 리스트를 담고 있는 메인 페이지 "/index.html"로 이동되고, 상단 우측의 `로그인` 버튼을 클릭하여 OAuth2를 활용한 소셜 아이디 로그인이 진행됨

<img width="1258" alt="image" src="https://github.com/HaiyoreNyarukoSan/portfolio-for-portfolio/assets/54230911/d1e9da45-00e4-4545-af03-a7cd6012522a">
