### ISSUE TITLE
IntelliJ Google Java Code Formatter 적용

### ISSUE THREAD

**Issue by donggrii** [HaiyoreNyarukoSan/portfolio-for-portfolio#4]
### IntelliJ에 Google Java Style Guide 적용

- 필요성 및 기대효과 : Google Coding Convention을 기반으로 코드 스타일을 일치시켜 코드 리뷰 시간 절약 등의 효율성 제고
- [참고 블로그](https://yeon-kr.tistory.com/197)의 내용을 그대로 적용하되, 아래 내용은 추가로 커스터마이징하기

1. GoogleStyle 적용 후, Tab size와 Indent : 2 → 4로 변경

![image](https://github.com/HaiyoreNyarukoSan/portfolio-for-portfolio/assets/54230911/389ce33c-b10f-4be6-bb91-735f126b1131)

2. Builder 패턴과 같은 chained method의 줄바꿈을 유지하기 위해 Align when multiline 체크

![image](https://github.com/HaiyoreNyarukoSan/portfolio-for-portfolio/assets/54230911/43c95b2d-2b50-408f-ae40-2302d175a394)

- 참고 : https://yeon-kr.tistory.com/197

**Comment by donggrii** [comment]
모두들 위 내용 적용하신 뒤, 댓글 남겨주시면 감사하겠습니다!

**Comment by note629** [comment]
설정 완료 했습니다

**Comment by Keeenex** [comment]
설정 완료했습니다.

**Comment by donggrii** [comment]
감사합니다. 이슈 이제 닫겠습니다.
