### ISSUE TITLE
Zergling.java 내용 추가 필요합니다.

### ISSUE THREAD

**Issue by HaiyoreNyarukoSan** [HaiyoreNyarukoSan/portfolio-for-portfolio#7]
#6 Pull request하면서 느낀 소감이 누락되었어요. 추가 부탁드립니다.

**Comment by note629** [comment]
강의 때 교육의 느낌에서 실전으로 넘어가는 느낌이 매우 색다르다고 느꼈습니다.

감사합니다.

![Image](https://github.com/HaiyoreNyarukoSan/SmallSpaceWar/assets/54761092/faed970c-80c0-4468-9b19-a4d12edbb4b1)
